# render.yaml

services:
  - type: web
    name: padel-clases
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "padel-clases.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: padel-db
          property: connectionString

databases:
  - name: padel-db
    databaseName: padel_db
    user: padel_user
