services:
  - type: web
    name: padel-clases
    env: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: padel-clases.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: padel-db
          property: connectionString
      - key: RENDER
        value: "true"
      - key: ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://padel-clases.onrender.com/api/
      - key: VITE_ENV
        value: production

databases:
  - name: padel-db
    databaseName: padel_db
    user: padel_user