# Generated by Django 4.2.20 on 2025-04-10 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha de la sesión de entrenamiento')),
                ('details', models.TextField(help_text='Descripción de lo entrenado')),
                ('teacher_comment', models.TextField(blank=True, help_text='Comentarios del profesor', null=True)),
                ('session_type', models.CharField(blank=True, help_text='Tipo de sesión (por ejemplo, individual, dúo, grupal)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'ordering': ['-date'],
            },
        ),
    ]
