# Generated by Django 4.2.20 on 2025-05-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
