# Generated by Django 4.2.20 on 2025-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_trainingsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnoperfil',
            old_name='paredes',
            new_name='agilidad',
        ),
        migrations.RenameField(
            model_name='alumnoperfil',
            old_name='pies',
            new_name='pared',
        ),
        migrations.RenameField(
            model_name='alumnoperfil',
            old_name='x3',
            new_name='pared_lateral',
        ),
        migrations.RenameField(
            model_name='alumnoperfil',
            old_name='x4',
            new_name='volea_natural',
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='mano_dominante',
            field=models.CharField(default='Derecha', max_length=20),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='posicion',
            field=models.CharField(default='Reves', max_length=20),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='volea_reves',
            field=models.IntegerField(default=0),
        ),
    ]
