# Generated by Django 4.2.20 on 2025-05-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_notificacion_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_password_reset_sent',
            field=models.DateTimeField(blank=True, help_text='Última vez que se envió un email de recuperación de contraseña.', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, help_text='Última vez que se envió un email de verificación.', null=True),
        ),
    ]
