# Generated by Django 4.2.20 on 2025-04-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_paredes_alumnoperfil_agilidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnoperfil',
            old_name='cambio_de_agarre',
            new_name='bote_pronto',
        ),
        migrations.RenameField(
            model_name='alumnoperfil',
            old_name='fisico',
            new_name='cambio_agarre',
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='potencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='resistencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='tecnica',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='velocidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='x3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='x4',
            field=models.IntegerField(default=0),
        ),
    ]
