# Generated by Django 4.2.20 on 2025-04-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_rename_cambio_de_agarre_alumnoperfil_bote_pronto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='chiquita',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='dejada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='reservas.caracteristica'),
        ),
    ]
