# Generated by Django 4.2.20 on 2025-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_caracteristica_alumnoperfil_chiquita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoperfil',
            name='contralateral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='contrapared',
            field=models.IntegerField(default=0),
        ),
    ]
