# Generated by Django 4.2.20 on 2025-04-15 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alumnoperfil_contralateral_alumnoperfil_contrapared'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_personalizados', to=settings.AUTH_USER_MODEL)),
                ('asignado_por', models.ForeignKey(blank=True, help_text='Profesor que asignó el recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso asignado',
                'verbose_name_plural': 'Recursos asignados',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
