# Generated by Django 4.2.20 on 2025-04-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_recursoalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursoalumno',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
