# Generated by Django 4.2.20 on 2025-04-16 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_recursoalumno_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_final',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(choices=[('individual', 'Individual'), ('pareja', 'Pareja'), ('grupal', 'Grupal')], default='individual', max_length=10),
        ),
    ]
