# Generated by Django 4.2.20 on 2025-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_reserva_hora_final_reserva_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
