# Generated by Django 4.2.20 on 2025-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_alter_reserva_hora_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursoalumno',
            old_name='descripcion',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='recursoalumno',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
