# Generated by Django 4.2.20 on 2025-04-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_rename_descripcion_recursoalumno_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(choices=[('individual', 'Individual'), ('pareja', 'Pareja'), ('grupal', 'Grupal')], default='individual', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('organizador', 'organizador')], max_length=15),
        ),
    ]
