# Generated by Django 4.2.20 on 2025-04-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_reserva_tipo_reserva_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('mixto', 'Mixto'), ('parejas', 'Por Parejas'), ('hombres', 'Solo Hombres'), ('mujeres', 'Solo Mujeres')], max_length=10)),
                ('num_pistas', models.PositiveIntegerField(default=8)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantePozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.FloatField()),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=10)),
                ('pista_fija', models.PositiveIntegerField(blank=True, null=True)),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='reservas.pozo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Afinidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('evitar', 'Evitar totalmente'), ('evitar_pareja', 'Evitar como pareja'), ('evitar_rival', 'Evitar como rival')], max_length=20)),
                ('con_participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evitado_por', to='reservas.participantepozo')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afinidades', to='reservas.participantepozo')),
            ],
        ),
    ]
