# Generated by Django 4.2.20 on 2025-04-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_pozo_participantepozo_afinidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('organizador', 'Organizador')], max_length=15),
        ),
        migrations.CreateModel(
            name='JugadorPozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.PositiveIntegerField()),
                ('registrado', models.BooleanField(default=False)),
                ('afinidades_negativas', models.ManyToManyField(blank=True, related_name='afinidades_negativas_de', to='reservas.jugadorpozo')),
                ('afinidades_positivas', models.ManyToManyField(blank=True, related_name='afinidades_positivas_de', to='reservas.jugadorpozo')),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='reservas.pozo')),
            ],
        ),
    ]
