# Generated by Django 4.2.20 on 2025-04-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_alter_usuario_rol_jugadorpozo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepozo',
            name='mano_dominante',
            field=models.CharField(choices=[('diestro', 'Diestro'), ('zurdo', 'Zurdo')], default='diestro', max_length=10),
        ),
    ]
