# Generated by Django 4.2.20 on 2025-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_participantepozo_mano_dominante'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepozo',
            name='posicion',
            field=models.CharField(choices=[('Reves', 'Reves'), ('Drive', 'Drive'), ('Ambos', 'Ambos')], default='Ambos', max_length=10),
        ),
    ]
