# Generated by Django 4.2.20 on 2025-04-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_participantepozo_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozo',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre amigable para identificar este pozo', max_length=100, verbose_name='Título del Pozo'),
        ),
    ]
