# Generated by Django 4.2.20 on 2025-04-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_pozo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='hombre', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor'), ('organizador', 'Organizador')], max_length=20),
        ),
    ]
