# Generated by Django 4.2.20 on 2025-04-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_usuario_fecha_nacimiento_usuario_localidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepozo',
            name='juega_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareja_forzada', to='reservas.participantepozo'),
        ),
        migrations.AddField(
            model_name='participantepozo',
            name='juega_contra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rival_forzado', to='reservas.participantepozo'),
        ),
        migrations.AddField(
            model_name='participantepozo',
            name='no_juega_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_pareja', to='reservas.participantepozo'),
        ),
        migrations.AddField(
            model_name='participantepozo',
            name='no_juega_contra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_rival', to='reservas.participantepozo'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(blank=True, help_text='Tipo de sesión', max_length=50, null=True),
        ),
    ]
