# Generated by Django 4.2.20 on 2025-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_participantepozo_juega_con_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantepozo',
            name='juega_con',
        ),
        migrations.RemoveField(
            model_name='participantepozo',
            name='juega_contra',
        ),
        migrations.RemoveField(
            model_name='participantepozo',
            name='no_juega_con',
        ),
        migrations.RemoveField(
            model_name='participantepozo',
            name='no_juega_contra',
        ),
        migrations.AlterField(
            model_name='participantepozo',
            name='posicion',
            field=models.CharField(choices=[('reves', 'Reves'), ('drive', 'Drive'), ('ambos', 'Ambos')], default='Ambos', max_length=10),
        ),
        migrations.AddField(
            model_name='participantepozo',
            name='juega_con',
            field=models.ManyToManyField(blank=True, related_name='es_pareja_de', to='reservas.participantepozo'),
        ),
        migrations.AddField(
            model_name='participantepozo',
            name='juega_contra',
            field=models.ManyToManyField(blank=True, related_name='es_rival_de', to='reservas.participantepozo'),
        ),
        migrations.AddField(
            model_name='participantepozo',
            name='no_juega_con',
            field=models.ManyToManyField(blank=True, related_name='no_debe_jugar_con', to='reservas.participantepozo'),
        ),
        migrations.AddField(
            model_name='participantepozo',
            name='no_juega_contra',
            field=models.ManyToManyField(blank=True, related_name='no_debe_jugar_contra', to='reservas.participantepozo'),
        ),
    ]
