# Generated by Django 4.2.20 on 2025-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_remove_participantepozo_juega_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantepozo',
            name='posicion',
            field=models.CharField(choices=[('reves', 'Reves'), ('drive', 'Drive'), ('ambos', 'Ambos')], default='ambos', max_length=10),
        ),
    ]
