# Generated by Django 4.2.20 on 2025-04-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_alter_participantepozo_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoperfil',
            name='anticipacion',
            field=models.IntegerField(default=0, verbose_name='Anticipación'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='competitividad',
            field=models.IntegerField(default=0, verbose_name='Competitividad'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='comunicacion',
            field=models.IntegerField(default=0, verbose_name='Comunicación'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='concentracion',
            field=models.IntegerField(default=0, verbose_name='Concentración'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='decisiones',
            field=models.IntegerField(default=0, verbose_name='Toma de Decisiones'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='esfuerzo',
            field=models.IntegerField(default=0, verbose_name='Esfuerzo'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='gestion_error',
            field=models.IntegerField(default=0, verbose_name='Gestión del Error'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='regularidad',
            field=models.IntegerField(default=0, verbose_name='Regularidad'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='serenidad',
            field=models.IntegerField(default=0, verbose_name='Serenidad'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='tactica',
            field=models.IntegerField(default=0, verbose_name='Táctica (General)'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='trabajo_equipo',
            field=models.IntegerField(default=0, verbose_name='Trabajo en Equipo'),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='vision_juego',
            field=models.IntegerField(default=0, verbose_name='Visión de Juego'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='onboarding_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumnoperfil',
            name='nivel',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='AlumnoPerfilEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('stats', models.JSONField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='reservas.alumnoperfil')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
