# Generated by Django 4.2.20 on 2025-04-30 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_alumnoperfil_anticipacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepozo',
            name='es_organizador',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
