# reservas/migrations/0024_participantepozo_es_organizador_pushtoken.py
# Generated by Django 4.2.20 on 2025-04-30 16:59

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_alumnoperfil_anticipacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantepozo',
            name='es_organizador',
            field=models.BooleanField(default=False),
        ),
        # ⚠️ Eliminado: PushToken ya existe en la base de datos y no debe recrearse.
    ]