# Generated by Django 4.2.20 on 2025-05-01 00:24

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_participantepozo_es_organizador_pushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozo',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título del Pozo'),
        ),
        migrations.AlterField(
            model_name='recursoalumno',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe una cuenta con este e-mail.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe una cuenta con este nombre de usuario.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
