# Generated by Django 4.2.20 on 2025-05-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_alter_pozo_titulo_alter_recursoalumno_asignado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, help_text='El usuario debe activar su cuenta vía email.'),
        ),
    ]
