# Generated by Django 4.2.20 on 2025-05-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0027_pushtoken'),
    ]

    operations = [
    ]
