# Generated by Django 4.2.20 on 2025-05-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0028_skip_duplicated_column'),
    ]

    operations = [
    ]
